baseURL = 'https://gw8ndal.github.io/'
DefaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true
title = 'Gwendal Troadec'
theme = 'beautifulhugo'
enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
    subtitle = "Mon site personnel, caverne d'Ali Baba de projets variés"
    dateFormat = "02/01/2006"
    socialShare = true
    hideAuthor = true
    favicon = 'img/logo.png'
    logo = 'img/logo.png'

[Author]
    name = "Gwendal Troadec"
    email = "gw8ndal@gmail.com"
    github = "gw8ndal"
    gitlab = "gw8ndal"
    twitter = "gw88ndal"
    linkedin = "gwendal-troadec"
    stackoverflow = "users/13027064/gwendal-troadec"
    instagram = "gw8ndal"

# Navbar
[[menu.main]]
    name = 'Projets'
    url = 'page/projets'
    weight = 1

[[menu.main]]
    name = 'A Propos'
    url = 'page/about'
    weight = 2

[languages]
    [languages.fr]
        languageName = "Français"
        contentDir = "content/fr"

    [languages.en]
        languageName = "English"
        contentDir = "content/en"
        [languages.en.params]
            subtitle = "My personal website, cave of wonders of various projects"
            dateFormat = "01/02/2006"
            [languages.en.menu]
[[languages.en.menu.main]]
      name = 'Projects'
      url = 'page/projets'
      weight = 1
[[languages.en.menu.main]]
      name = 'About'
      url = 'page/about'
      weight = 2